export const MYORDER_RQUEST="MYORDER_RQUEST";
export const MYORDER_SUCCESS="MYORDER_SUCCESS";
export const MYORDER_FAIL="MYORDER_FAIL";
export const CLEAR_ERRORS="CLEAR_ERRORS";


export const ALL_ORDER_RQUEST="ALL_ORDER_RQUEST";
export const  ALL_ORDER_SUCCESS="ALL_ORDER_SUCCESS";
export const  ALL_ORDER_FAIL="ALL_ORDER_FAIL";



export const UPDATE_ORDER_STATUS_REQUEST="UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS="UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAIL="UPDATE_ORDER_STATUS_FAIL";


export const DELETE_ORDER_REQUEST="DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS="DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL="DELETE_ORDER_FAIL";

export const STATUS_EDIT_SUCCESS="STATUS_EDIT_SUCCESS";
export const STATUS_EDIT_FAIL="STATUS_EDIT_FAIL";
export const STATUS_EDIT_REQUEST="STATUS_EDIT_REQUEST";


