export const ALL_PRODUCT_RQUEST="ALL_PRODUCT_RQUEST";
export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL";
export const CLEAR_ERRORS="CLEAR_ERRORS";


export const PRODUCT_RQUEST="PRODUCT_RQUEST";
export const PRODUCT_SUCCESS="PRODUCT_SUCCESS";
export const PRODUCT_FAIL="PRODUCT_FAIL";



export const NEW_PRODUCT_RQUEST="NEW_PRODUCT_RQUEST";
export const NEW_PRODUCT_SUCCESS="NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_FAIL="NEW_PRODUCT_FAIL";


