export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";
export const  CLEAR_ERRORS="CLEAR_ERRORS";


export const REGISTER_REQUEST="REGISTER_REQUEST";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";



export const LOADUSER_REQUEST="LOADUSER_REQUEST";
export const LOADUSER_SUCCESS="LOADUSER_SUCCESS";
export const LOADUSER_FAIL="LOADUSER_FAIL";


export const LOGOUT_REQUEST="LOGOUT_REQUEST";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAIL="LOGOUT_FAIL";



export const UPDATE_PASSWORD_REQUEST="UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS="UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL="UPDATE_PASSWORD_REQUEST_FAIL";
export const UPDATE_PASSWORD_RESET="UPDATE_PASSWORD_REQUEST_RESET";



export const FROGOT_PASSWORD_REQUEST="FROGOT_PASSWORD_REQUEST";
export const FROGOT_PASSWORD_SUCCESS="FROGOT_PASSWORD_SUCCESS";
export const FROGOT_PASSWORD_FAIL="FROGOT_PASSWORD_FAIL";


export const RESET_PASSWORD_REQUEST="RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS="RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL="RESET_PASSWORD_FAIL";



export const  USERUPDATE_REQUEST="USERUPDATE_REQUEST";
export const USERUPDATE_SUCCESS="USERUPDATE_SUCCESS";
export const USERUPDATE_FAIL="USERUPDATE_FAIL";




export const  ALLUSER_REQUEST="ALLUSER_REQUEST";
export const ALLUSER_SUCCESS="ALLUSER_SUCCESS";
export const ALLUSER_FAIL="ALLUSER_FAIL";



export const  EDITUSER_ROLE_REQUEST="EDITUSER_ROLE_REQUEST";
export const  EDITUSER_ROLE_SUCCESS="EDITUSER_ROLE_SUCCESS";
export const  EDITUSER_ROLE_FAIL="EDITUSER_ROLE_FAIL";
